baseURL = "https://physical-design-interview-guide.github.io/"
languageCode = "en-us"
title = "Physical Design Interview Guide"
theme = "nordic"
paginate = 6

[pagination]
  pagerSize = 6
enableRobotsTXT = true
summaryLength = 60

[params]
  description = "The Ultimate Guide to Physical Design Interview Questions"
  logo = "/img/physical-design-interview-guide-small.jpg"
  favicon = "/img/physical-design-interview-guide-small.jpg"
  defaultTheme = "light"   # "light" or "dark"
  
  author       = "Gautam"
  authorBio    = "VLSI Physical Design Engineer with industry experience"
  siteLanguage = "en-US"
  # Social (used in footer/schema â€” fill in yours)
  twitter      = ""
  linkedin     = ""


[taxonomies]
  category = "categories"

# Navigation tabs
[menu]
  [[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1
  [[menu.main]]
    name   = "General-Concepts"
    url    = "/categories/general-concepts/"
    weight = 2
  [[menu.main]]
    name   = "Pre-PnR"
    url    = "/categories/pre-pnr/"
    weight = 3
  [[menu.main]]
    name   = "Floorplan"
    url    = "/categories/floorplan/"
    weight = 4
  [[menu.main]]
    name   = "Power-Plan"
    url    = "/categories/power-plan/"
    weight = 5
  [[menu.main]]
    name   = "Placement"
    url    = "/categories/placement/"
    weight = 6
  [[menu.main]]
    name   = "CTS"
    url    = "/categories/cts/"
    weight = 7
  [[menu.main]]
    name   = "Routing"
    url    = "/categories/routing/"
    weight = 8
  [[menu.main]]
    name   = "ECO"
    url    = "/categories/eco/"
    weight = 9
  [[menu.main]]
    name   = "STA"
    url    = "/categories/sta/"
    weight = 10
  [[menu.main]]
    name   = "SI"
    url    = "/categories/signal-integrity/"
    weight = 11
  [[menu.main]]
    name   = "PV"
    url    = "/categories/physical-verification/"
    weight = 12
  [[menu.main]]
    name   = "About Me"
    url    = "/about/"
    weight = 13
#  [[menu.main]]
#    name   = "Privacy Policy"
#    url    = "/privacy-policy/"
#    weight = 14

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true   # allows raw HTML in markdown posts
      
[sitemap]
  changefreq = "weekly"
  priority   = 0.8
  filename   = "sitemap.xml"
